apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuttleverse-service-discovery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shuttleverse-service-discovery
  template:
    metadata:
      labels:
        app: shuttleverse-service-discovery
    spec:
      containers:
        - name: shuttleverse-service-discovery
          image: docker-user/shuttleverse-service-discovery:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: shuttleverse-service-discovery
  namespace: default
spec:
  selector:
    app: shuttleverse-service-discovery
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP